### ISSUE TITLE
Fulltext generation from HTML Content

### ISSUE THREAD

**Issue by MRuecklCC** [openeduhub/metalookup#146]
One big problem when scraping content, is that the fulltext is often not trivially accessible. 

Instead, we have the whole DOM HTML document. One approach would be to use the html roles: https://wiki.selfhtml.org/wiki/HTML/Attribute/role

One approach would be to check if a "main content role is available and remove everything else.
Alternatively one can start removing elements that are of different roles (like navigation bar, footer, etc).

**Comment by MRuecklCC** [comment]
Jörg from @yovisto found the amazing python package [travilatura](https://trafilatura.readthedocs.io/en/latest/) which seems to do a pretty good job at solving this issue.

It also provides other metadata like
- author
- license
- keyword
- title

which we could all expose via metalookup.

**Comment by lummerland** [comment]
Resolved with https://github.com/openeduhub/text-extraction
